#!/bin/bash
#SBATCH --job-name=CORE_HL60_500_1
#SBATCH --mem-per-cpu=6000
#SBATCH --cpus-per-task=4
#SBATCH -m block

#SBATCH --partition=longq
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --output src_pipeline/slurm/CORE_HL60_500_1_wgbs.log

echo 'Compute node:' `hostname`
echo 'Start time:' `date +'%Y-%m-%d %T'`

python src_pipeline/wgbs_pipeline.py -i /fhgfs/groups/lab_bock/jklughammer/projects/otherProjects/CORE-seq/titration/CORE/unmapped_bam/BSF_0131_C5FD6ACXX_8__CORE_HL60_500_1.bam -s CORE_HL60_500_1


